### ISSUE TITLE
Possible conflict between Combustible Lemon Launcher and Weather 2.

### ISSUE THREAD

**Issue by adamvan2000** [Phlenum/Combustible-Lemon-Launcher#2]
Forge: 11.15.1.1734
CLL: 3.0.9
Weather 2: 2.3.11

I keep getting this error every time I open my inventory. I'm not sure that this is a CLL issue.

```
[18:39:00] [Client thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.client.event.RenderLivingEvent$Pre@75d57e5e:
java.lang.NullPointerException
	at mods.phlenum.cll.client.HoldLikeBowHook.onEntityLiving(HoldLikeBowHook.java:32) ~[HoldLikeBowHook.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_382_HoldLikeBowHook_onEntityLiving_Pre.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:55) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraft.client.renderer.entity.RendererLivingEntity.func_76986_a(RendererLivingEntity.java:89) [bjl.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:63) [bln.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:23) [bln.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147939_a(RenderManager.java:375) [biu.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_147940_a(RenderManager.java:355) [biu.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.func_147046_a(SourceFile:94) [azc.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.func_146976_a(SourceFile:60) [azc.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75) [ayl.class:?]
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:49) [ayw.class:?]
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47) [azc.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:309) [ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1103) [bfk.class:?]
	at weather2.weathersystem.EntityRendererProxyWeather2Mini.func_181560_a(EntityRendererProxyWeather2Mini.java:50) [EntityRendererProxyWeather2Mini.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051) [ave.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349) [ave.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

[fml-client-latest.txt](https://github.com/Phlenum/Combustible-Lemon-Launcher/files/133617/fml-client-latest.txt)

**Comment by Corosauce** [comment]
It's just passing through EntityRendererProxyWeather2Mini, highly unlikely it is related to this issue at all.
